if(CMAKE_CROSSCOMPILING)
    set(PERL_CORE_DIR ${CMAKE_SYSROOT}/usr/lib/arm-linux-gnueabihf/perl/5.24/CORE)
    set(PERL_INCLUDE_DIR ${PERL_CORE_DIR})
    set(PERL_LIB_DIR ${CMAKE_SYSROOT}/usr/lib/arm-linux-gnueabihf/)
    find_library(LIB_PERL NAMES perl HINTS ${PERL_LIB_DIR} REQUIRED)
    find_library(LIB_M NAMES m HINTS ${PERL_LIB_DIR} REQUIRED)
elseif(CMAKE_SYSTEM_NAME STREQUAL Darwin)
    set(PERL_CORE_DIR /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Perl/5.34/darwin-thread-multi-2level/CORE)
    set(PERL_INCLUDE_DIR ${PERL_CORE_DIR})
    set(PERL_LIB_DIR /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Perl/5.34/darwin-thread-multi-2level/CORE)
    find_library(LIB_PERL NAMES perl HINTS ${PERL_LIB_DIR} REQUIRED)
    find_library(LIB_M NAMES m REQUIRED)
endif()

